// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go-drive/common"
	"go-drive/common/i18n"
	"go-drive/common/registry"
	"go-drive/common/task"
	"go-drive/common/utils"
	"go-drive/drive"
	"go-drive/server"
	"go-drive/storage"
)

// Injectors from wire.go:

func Initialize(ch *registry.ComponentsHolder) (*gin.Engine, error) {
	config, err := common.InitConfig(ch)
	if err != nil {
		return nil, err
	}
	db, err := storage.NewDB(config, ch)
	if err != nil {
		return nil, err
	}
	driveDAO := storage.NewDriveDAO(db)
	pathMountDAO := storage.NewPathMountDAO(db)
	driveDataDAO := storage.NewDriveDataDAO(db)
	driveCacheDAO := storage.NewDriveCacheDAO(db, ch)
	rootDrive, err := drive.NewRootDrive(config, driveDAO, pathMountDAO, driveDataDAO, driveCacheDAO)
	if err != nil {
		return nil, err
	}
	fileTokenStore, err := server.NewFileTokenStore(config, ch)
	if err != nil {
		return nil, err
	}
	thumbnail, err := server.NewThumbnail(config, ch)
	if err != nil {
		return nil, err
	}
	signer := utils.NewSigner()
	chunkUploader, err := server.NewChunkUploader(config)
	if err != nil {
		return nil, err
	}
	tunnyRunner := task.NewTunnyRunner(config, ch)
	userDAO := storage.NewUserDAO(db)
	groupDAO := storage.NewGroupDAO(db)
	pathPermissionDAO := storage.NewPathPermissionDAO(db)
	fileMessageSource, err := i18n.NewFileMessageSource(config)
	if err != nil {
		return nil, err
	}
	engine := server.InitServer(config, ch, rootDrive, fileTokenStore, thumbnail, signer, chunkUploader, tunnyRunner, userDAO, groupDAO, driveDAO, driveCacheDAO, driveDataDAO, pathPermissionDAO, pathMountDAO, fileMessageSource)
	return engine, nil
}
